Redis retry support
radekmie/changestream-to-redis pull request #6
Opened 2024-12-04 16:03 UTC by jdgjsag67251

Added retry functionality to Redis to prevent an event from potentially being dropped

2024-12-09 07:51 UTC, radekmie requested changes
Also, could you share how often it happens to you? We've never witnessed anything like it.

2024-12-09 07:51 UTC, radekmie commented on src/ejson.rs
> +    fn to_ejson(&self) -> Value;
Where is this change coming from? Currently `into_json` consumes its value and that's expected - we don't want to `clone` as long as possible. Ther is one "big" `clone` in a `if config.debug` branch, but that's not a problem, as `debug` is not intended for production use.

2024-12-09 07:51 UTC, radekmie commented on src/redis.rs
> +            )
It looks like [`get_tokio_connection_manager_with_backoff_and_timeouts` is deprecated](https://docs.rs/redis/0.27.6/redis/struct.Client.html#method.get_tokio_connection_manager_with_backoff_and_timeouts) in favor of [`get_connection_manager_with_config`](https://docs.rs/redis/0.27.6/redis/struct.Client.html#method.get_connection_manager_with_config) added in a newer version. This would allow us to get rid of these arbitrary constants (all `ConnectionManager`-related options should be optional).

2024-12-09 07:51 UTC, radekmie commented on src/main.rs
> +        }
This is not ideal either, as it's always doing a retry (no matter what the error is) and always does it exactly once (I believe some people may want to do it more often).

2024-12-09 08:30 UTC, jdgjsag67251 commented on src/redis.rs
> +            )
Yeah, I wasn't sure if I could update the version so I made it work with the current one. I'll update package

2024-12-09 08:56 UTC, radekmie commented on src/redis.rs
> +            )
Just please check the changelog before 😅

2024-12-09 10:47 UTC, jdgjsag67251 commented on src/ejson.rs
> +    fn to_ejson(&self) -> Value;
For retries I had to clone the `Event` somewhere. I wanted to move the clone to the smallest part. But I agree that this is also not ideal. I'll try to come up with a better solution

2024-12-09 10:49 UTC, jdgjsag67251 commented
> Also, could you share how often it happens to you? We've never witnessed anything like it.

We run this on Azure Container Apps and for some inexplicable reason that just randomly drops connections.
We've contacted Microsoft support and they are looking into it. In the mean time this change made it work for us

2024-12-09 10:51 UTC, jdgjsag67251 commented on src/main.rs
> +        }
Yeah I looked into the error type, but it did not include the reason as an enum, so I couldn't determine if it was a connection issue or a Redis issue. I just opted for always retrying since that will probably just fail again in the case of a Redis error.

2024-12-10 14:55 UTC, rikvdlooi commented
Azure: 

![image](https://github.com/user-attachments/assets/48a37fa2-de13-40f6-a16c-571f83a50eef)

Every 5 minutes it loses connection. With this fix applied we do not see any issues anymore.
This is an issue with Azure (Container Apps), however their engineers are unable to locate the issue on their end. This PR fixes it on the app side.

2024-12-11 20:46 UTC, radekmie commented
Sorry but I couldn't resist the urge to _adjust_ it a little 😅 I did the following:
* In `README.md`:
    * Changed the links to `redis` docs to link the exact version we're using.
    * Removed defaults if they came from `redis` (I assume it's self explanatory via the docs link).
    * Sorted flags.
* In configuration:
    * Moved `ConnectionManagerConfig` to `Config` class. (There's `clone` involved, but it's very cheap and allowed me centralize it there in one field. In the future I'd like to use `clap` or something similar.)
* In Redis connection:
    * Inlined most of the logic back into `publish`. I did that only because I changed the retry loop a little and I think it's not "too big" to fit in there.

Overall, I'm really happy with the way it works! Please, do test it and let me know if it's all good now. If it will, I'll publish a new release on Friday.

Thanks again!

2024-12-11 20:47 UTC, radekmie approved these changes

2024-12-12 09:25 UTC, jdgjsag67251 commented
> Sorry but I couldn't resist the urge to _adjust_ it a little 😅 I did the following:
> 
>     * In `README.md`:
>       
>       * Changed the links to `redis` docs to link the exact version we're using.
>       * Removed defaults if they came from `redis` (I assume it's self explanatory via the docs link).
>       * Sorted flags.
> 
>     * In configuration:
>       
>       * Moved `ConnectionManagerConfig` to `Config` class. (There's `clone` involved, but it's very cheap and allowed me centralize it there in one field. In the future I'd like to use `clap` or something similar.)
> 
>     * In Redis connection:
>       
>       * Inlined most of the logic back into `publish`. I did that only because I changed the retry loop a little and I think it's not "too big" to fit in there.
> 
> 
> Overall, I'm really happy with the way it works! Please, do test it and let me know if it's all good now. If it will, I'll publish a new release on Friday.
> 
> Thanks again!

Oh yeah no of course, it's your project after all =). Thanks for the quick response!
Seems to work well with the new changes, so I'm also very happy!

2024-12-13 07:02 UTC, merged